# Generated by Django 5.1.6 on 2025-04-26 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('ping_ms', models.FloatField(blank=True, null=True)),
                ('download_speed_kbps', models.FloatField(blank=True, null=True)),
                ('upload_speed_kbps', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
