# Generated by Django 5.2 on 2025-05-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_trafficlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtestresult',
            name='ping_ms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
