# Generated by Django 5.2 on 2025-05-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_speedtestresult_ping_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtestresult',
            name='ping_ms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
