# Generated by Django 5.2 on 2025-05-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_speedtestresult_ping_ms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commands',
            options={'verbose_name': 'Buýruk', 'verbose_name_plural': 'Buýruklar'},
        ),
        migrations.AlterModelOptions(
            name='searchquery',
            options={'verbose_name': 'Gozleg', 'verbose_name_plural': 'Gozlegler'},
        ),
    ]
